require 'global'
require 'settings'
require 'keybindings'
require 'plugins'

require 'nv-lspconfig'
require 'nv-compe'
require 'nv-vsnip'

require 'nv-nvimtree'
require 'nv-treesitter'
require 'nv-lspkind'
require 'nv-trouble'
require 'nv-gitsigns'
require 'nv-floaterm'
require 'nv-bufferline'
require 'nv-neoscroll'
require 'nv-autopairs'
require 'nv-telescope'
require 'nv-colorizer'
require 'nv-galaxyline'
require 'nv-themes'
