return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "c_sharp",
      "cmake",
      "css",
      "diff",
      "dockerfile",
      "html",
      "go",
      "gitignore",
      "gomod",
      "gowork",
      "java",
      "json",
      "javascript",
      "python",
      "make",
      "markdown",
      "markdown_inline",
      "lua",
      "vim",
      "yuck",
      "yaml",
    },
  },
}
