return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cpp",
      "css",
      "cmake",
      "comment",
      "diff",
      "dockerfile",
      "fish",
      "go",
      "gomod",
      "html",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "make",
      "markdown",
      "markdown_inline",
      "python",
      "regex",
      "scss",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "yuck",
    },
  },
}
