return {
  "nvim-treesitter/nvim-treesitter",
  indent = { enable = false },
  highlight = { enable = true },
  folds = { enable = true },
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "query",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "hyprland",
    },
    vim.filetype.add({
      pattern = {
        [".*/hypr/.*%.conf"] = "hyprlang",
      },
    }),
  },
}
